name: swapxchange
description: Sell/Swap stuff nearby

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.8+8

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  fluttertoast: ^8.0.6

  #intl(FOR DATE AND CO...)
  intl: ^0.17.0

  firebase_core: ^1.1.0 #FOR FIREBASE APP INITIALIZATION
  #   For handling authentication via firebase
  firebase_auth: ^1.1.3
  #  FCM
  firebase_messaging: ^10.0.0

#   firebase storage
  firebase_storage: ^10.0.5
#   For making request to fire store database
  cloud_firestore: ^2.5.3

  # For handling facebook sign in
  #https://stackoverflow.com/questions/27448684/android-facebook-sdk-generate-release-key-hash
  flutter_facebook_auth: ^3.3.3+1

  # Shimmer effect library
  shimmer: ^1.1.2

  # Gradient app bar
  gradient_app_bar: ^0.1.3

  # image_picker
  image_picker: ^0.7.1
  flutter_image_compress: ^1.0.0
#  Multi image picker
#  multi_image_picker: ^4.8.0

  # path provider
  path_provider: ^2.0.1

  # cached network image
  cached_network_image: ^3.0.0

  # agora rtc engine
  agora_rtc_engine: ^4.0.7

  # permission handler
  permission_handler: ^6.1.3

  #  image compressor
  wechat_assets_picker: ^5.1.3
  animated_text_kit: ^4.2.1

  #Http calls
  dio: ^4.0.0

  #  Geocoding
  geolocator: ^7.0.3 #get lat long
  geocoding: ^2.0.0 #get address from lat long

  #  Shared preferences
  shared_preferences: ^2.0.5
#  State management & routing
  get: ^4.1.4
  font_awesome_flutter: ^9.0.0
  google_fonts: ^2.0.0
  animations: ^2.0.0
  web_socket_channel: ^2.1.0
  enum_to_string: ^2.0.1
  collection: ^1.15.0
  rxdart: ^0.27.0
  flutter_paystack: ^1.0.5+1
  share: ^2.0.4
  google_maps_flutter: ^2.0.6
  flutter_local_notifications: ^6.0.0
  country_code_picker: ^2.0.2
  flutter_html: ^2.1.1
  awesome_dialog: ^2.1.1
  url_launcher: ^6.0.9
  universal_html: ^2.0.8 #decode html entities
  encrypt: ^5.0.1
  flutter_dotenv: ^5.0.2
  crypto: ^3.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - images/


